---
title: "TPS"
author: "Tyler Stephen"
date: '2017-03-28'
output: pdf_document
---
```{r read data, ref.label="data helpers", echo=FALSE}
tps100 <- readTPS("100-tps.csv")
tps1000 <- readTPS("1000-tps.csv")
multiqs1 <- readTPS("tps_1000u1q.csv")
multiqs2 <- readTPS("tps_1000u2q.csv")
multiqs3 <- readTPS("tps_1000u3q.csv")
w7 <- readTPS("tps_1000u7w.csv")
w8 <- readTPS("tps_1000u8w.csv")
w9 <- readTPS("tps_1000u9w.csv")
w10 <- readTPS("tps_1000u10w.csv")
w11 <- readTPS("tps_1000u11w.csv")
w12 <- readTPS("tps_1000u12w.csv")
f2016 <- readTPS("tps_final2016.csv")
```

```{r plot 100 v. 1000, ref.label="plot helpers", echo=FALSE}
xrange <- range(0, 60)
maxTPS <- max(tps100$tps, tps1000$tps)
yrange <- range(0, maxTPS)
colors <- c("red", "blue")

# Set up plot
plot(xrange, yrange,   
     type = "n", 
     xlab = "Runtime (s)", 
     ylab = "TPS"
     )

addLine(tps100, colors[1])
addLine(tps1000, colors[2])

legend(xrange[1],
       yrange[2],
       c("100", "1000"),
       cex = 0.8,
       lwd = 1.5,
       col = colors,
       title = "Users"
       )
```

```{r plot multi-qs, ref.label="plot helpers", echo=FALSE}
xrange <- range(0, 70)
maxTPS <- max(multiqs1$tps, multiqs2$tps, multiqs3$tps, w8$tps)
yrange <- range(0, maxTPS)
linetypes <- c(1, 2, 3)
colors <- c("blue", "red")

plot(xrange, yrange,
     type = "n",
     xlab = "Runtime (s)",
     ylab = "TPS"
     )

addLine(multiqs1, col = colors[1], lty = linetypes[1])
addLine(multiqs2, col = colors[1], lty = linetypes[2])
addLine(multiqs3, col = colors[1], lty = linetypes[3])
addLine(tps1000, col = colors[2])

legend(xrange[1], yrange[2],
       1:3,
       cex = 0.8,
       lwd = 1.5,
       lty = linetypes,
       col = "blue",
       title = "Quote servers"
       )

legend(xrange[2] - 11, yrange[2],
       c("Multi", "Single"),
       cex = 0.8,
       lwd = 1.5,
       col = colors,
       title = "Architecture"
       )
```

```{r plot min workers, ref.label="plot helpers", echo=FALSE}
xrange <- range(0, 90)
maxTPS <- max(w7$tps, w8$tps)
yrange <- range(0, maxTPS)
colors <- c("blue", "red")

plot(xrange, yrange,
     type = "n",
     xlab = "Runtime (s)",
     ylab = "TPS"
     )

addLine(w7, col = colors[1])
addLine(w8, col = colors[2])

legend(xrange[1], yrange[2],
       7:8,
       cex = 0.8,
       lwd = 1.5,
       col = colors,
       title = "Workers"
       )
```

```{r plot max workers, ref.label="plot helpers", echo=FALSE}
xrange <- range(0, 60)
maxTPS <- max(w8$tps, w9$tps, w10$tps, w11$tps, w12$tps)
yrange <- range(0, maxTPS)
numRuns <- 5
linetypes <- 2:(numRuns+1) 

plot(xrange, yrange,
     type = "n",
     xlab = "Runtime (s)",
     ylab = "TPS"
     )

addLine(w8, lty = linetypes[1])
addLine(w9, lty = linetypes[2])
addLine(w10, lty = linetypes[3])
addLine(w11, lty = linetypes[4])
addLine(w12, lty = linetypes[5])

legend(xrange[1], yrange[2],
       8:12,
       cex = 0.8,
       lwd = 1.5,
       lty = linetypes,
       title = "Workers"
       )
```

```{r worker scaling, echo=FALSE}
tpsPerWorker = c()
tpsPerWorker[7]  = getTpsPerWorker(w7, 7)
tpsPerWorker[8]  = getTpsPerWorker(w8, 8)
tpsPerWorker[9]  = getTpsPerWorker(w9, 9)
tpsPerWorker[10] = getTpsPerWorker(w10, 10)
tpsPerWorker[11] = getTpsPerWorker(w11, 11)
tpsPerWorker[12] = getTpsPerWorker(w12, 12)

workers <- 7:12
xrange <- range(7, 12)
yrange <- range(3500, 4000)

plot(xrange, yrange,
     type = "n",
     xlab = "Workers",
     ylab = "Nominal TPS per worker"
     )

for (i in workers) {
  points(i, tpsPerWorker[i])
}

# Best fit line
fit <- lm(tpsPerWorker[workers]~workers)
abline(coef(fit)[1:2])

# Round coefficients for display on plot
cf <- round(coef(fit), 2)
eq <- paste0("TPS per worker = ",
             cf[1],
             ifelse(sign(cf[2])==1, " + ", " - "), abs(cf[2]), "*workers"
             )
mtext(eq, 3, line = -2)

# Show the R^2
r2 <- round(summary(fit)$adj.r.squared, 4)
r2eq <- paste0("R^2 = ", r2)
mtext(r2eq, 3, line = -3)
```
```{r plot mega quotes, ref.label="plot helpers", echo=FALSE}
xrange <- range(0, 60)
maxTPS <- max(w12$tps, f2016$tps)
yrange <- range(0, maxTPS)
colors <- c("blue", "red")

plot(xrange, yrange,
     type = "n",
     xlab = "Runtime (s)",
     ylim = c(0, 50000),
     ylab = "TPS"
     )

addLine(w12, col = colors[1])
addLine(f2016, col = colors[2])

legend(xrange[1], yrange[2],
       c(1000, 2000),
       cex = 0.8,
       lwd = 1.5,
       col = colors,
       title = "Quotes"
       )
```

```{r plot helpers, echo=FALSE}
addLine <- function(d, col, lty) {
  if (missing(col)) { col <- "black" }
  if (missing(lty)) { lty <- 1 }
  
  lines(d$time, d$tps, lwd = 1.5, col = col, lty = lty)
}
```

```{r data helpers, echo=FALSE}
readTPS <- function(filename) {
  tpsData <- read.csv(filename, header = F, col.names = c("time"), colClasses = c("numeric"))
  
  # Make times relative to start time
  minTime <- min(tpsData$time)
  tpsData$time <- tpsData$time - minTime
  
  # table() groups, counts matching time entries
  tpsData <- as.data.frame(table(tpsData$time))
  
  # Convert back to nice data types
  names(tpsData) <- c("time", "tps")
  tpsData <- transform.data.frame(tpsData, time = as.numeric(time), tps = as.numeric(tps))
  
  return(tpsData)
}

getTpsPerWorker <- function(d, numWorkers) {
  nominalRate <- max(d$tps) * 0.85
  nominalData <- subset(d, tps >= nominalRate)
  return(mean(nominalData$tps) / numWorkers)
}
```
