---
title: "Worker backlog"
author: "Tyler Stephen"
date: '2017-03-26'
output: pdf_document
---

```{r read data, echo=FALSE}
cls <- c(round="numeric", worker="numeric", backlog="numeric")
load100 <- read.csv("load_100.csv", header = T, colClasses = cls)
load1000 <- read.csv("load_1000.csv", header = T, colClasses = cls)
```

```{r plot worker backlog, echo=FALSE}
# determine bounds for plot based on 1000 user load since it's... larger
xrange <- range(load1000$round)
yrange <- range(0,load1000$backlog)
numWorkers <- max(load100$worker)

# Set up plot
plot(xrange, yrange, 
     type = "n", 
     xlim = range(0, 40),
     xlab = "Sending round", 
     ylab = "Backlog in workers"
     )

colors <- c("red", "blue")
linetype <- c(1:numWorkers)
plotchar <- seq(18, 18+numWorkers, 1)

# Add plot lines
for (i in 1:numWorkers) {
  load100Worker <- subset(load100, worker == i)
  lines(load100Worker$round, load100Worker$backlog,
        type = "b",
        lwd = 1.5,
        lty = linetype[i],
        col =  colors[1],
        pch = plotchar[i]
        )
  
  load1000Worker <- subset(load1000, worker == i)
  lines(load1000Worker$round, load1000Worker$backlog,
        type = "b",
        lwd = 1.5,
        lty = linetype[i],
        col = colors[2],
        pch = plotchar[i]
        )
}

title("Unprocessed transactions in worker after each load cycle", "Cycle = 3300 transactions; Rounds approx 1sec")

legend(xrange[1],
       yrange[2],
       c("100", "1000"),
       cex = 0.8,
       title = "Users",
       col = colors,
       lwd = 1
       )
legend(xrange[length(xrange)] - 3, # right align
       yrange[2],
       1:numWorkers,
       cex = 0.8,
       pch = plotchar,
       title = "Worker"
       )
```
